name: py

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: execute py script # run file
        run: |
            python -u main.py

      - name: Add and Commit changes
        run: |
          git config --local user.email 'compile@example.com'
          git config --local user.name 'WAMO Helper'
          git add --all
          git diff-index --quiet HEAD || git commit -m 'Flask Source Compile: ${{ github.event.head_commit.message }}'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main